# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AircraftLocalizationVisDialog
                                 A QGIS plugin
 Visualize Sensor network and data from aircrafts
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-20
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Iryna Ryabokin
        email                : riabokin.iryna1122@vu.cdu.edu.ua
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'aircraft_localization_vis_dialog_base.ui'))


class AircraftLocalizationVisDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(AircraftLocalizationVisDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.toolButtonChooseSensorsFile.clicked.connect(self.selectSensorsFile)
        self.toolButtonChooseDataFilename.clicked.connect(self.selectAircraftDataFile)

    def selectSensorsFile(self):
        filename, _filter = QFileDialog.getOpenFileName(
            self, "Файл з інформацією про сенсори","", '*.csv')
        self.lineEditSensorsFilename.setText(filename)

    def selectAircraftDataFile(self):
        filename, _filter = QFileDialog.getOpenFileName(self, "Файл з інформацією про літаки","", '*.csv')
        self.lineEditPackagesFilename.setText(filename)
